### ISSUE TITLE
Does still someone worked on this 

### ISSUE THREAD

**Issue by ghost** [exercism/clojure#365]
hello, 

As the title says I wonder if someone still works on this 

Roelof

**Comment by porkostomus** [comment]
I understand why one would wonder this. Exercism is cited in just about every collection of Clojure learning resources I see, so you would think it would be receiving much more love. I started out as a mere learner on the Clojure Track, then started mentoring, and gradually took on more maintenance responsibilities out of a realization that *If I don't, who will?*

But I am not even a real developer... I started learning to code in hope of one day getting off the street... a hope which still remains. Until then, I'm just a small person trying to help this platform continue since so many folks like myself benefit from it.

I have a paranoid fear that I have, in my enthusiasm, given the impression that I am capable of contributing more than I am able to, scaring away other potential maintainers in the process. So let it be made clear that all are welcome to get more involved and I will happily make every effort to familiarize others with what I've done, and we can work together to make the Clojure (and also [Babashka!](https://github.com/exercism/babashka) track the best it can be!

In fact, it's the kind of collaboration that is desperately needed in my life right now.

**Comment by RoelofWobben** [comment]
Oke, 

Thanks for the answers. 
I m trying to learn clojure but need a lot of help to make things work.
Worked trough the brave book and still feel like a super beginner.
So I do not think I can help you a lot. 

Roelof

**Comment by porkostomus** [comment]
Ah, Clojure Brave, yet another labor of love! I recall Daniel Higginbothom, the author, expressing on a Clojure podcast that releasing a book for free online may not have been the best move concerning self financial interest. And it remains the single-most referenced work for beginning the Clojure language. Love it!

Some people (like @seancorfield) have mentioned that they don't particularly care for the book's often jocular tone... but then, Mike Thompson (author of [re-frame](https://github.com/day8/re-frame) said once on the [Clojurescript Podcast](https://clojurescriptpodcast.com/) that a certain percentage of the population basically lacks a sense of humor...

**Comment by seancorfield** [comment]
It's true! I have absolutely no sense of humour whatsoever and that's because I'm British. Allegedly.

**Comment by RoelofWobben** [comment]
I like the book because all topics are in small pieces with challenges.

**Comment by RoelofWobben** [comment]
and is there a sort of list with concepts ?

**Comment by porkostomus** [comment]
> But I understand that you are the only maintainer ?

Yes actually that's part of the problem, because we follow a strict review policy so if no one is willing to review a PR then it just sits there and progress stalls. This is unfortunate, because at this time we are trying to encourage bold progress (i.e. merge now / fix later).

It is not hopeless, however. @ErikSchierboom is always happy to help out. Others too. In fact, it's probably the kindest group of volunteers I've ever seen, which is why I enjoy it so much :)

**Comment by RoelofWobben** [comment]
Nice to hear

**Comment by ErikSchierboom** [comment]
Yep, I'm always there to help! Coincidentally, I'm learning Clojure myself :)

**Comment by RoelofWobben** [comment]
@ErikSchierboom  What resource do you then use to learn clojure ?

**Comment by ErikSchierboom** [comment]
Just google

**Comment by RoelofWobben** [comment]
oke, I have used the brave book and 4clojure challenges to learn clojure.
