### ISSUE TITLE
Concept Exercises and Practice Exercises use different project files

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/clojure#374]
The Practice Exercises all have a `project.clj` file, whereas the Concept Exercises instead have `deps.edn` file. I have no idea which is better, but when testing on exercism.lol, I found that Concept Exercises were not tested correctly due to the test runner expecting a `project.clj` file. It is probably best to use just one format.

**Comment by porkostomus** [comment]
I had decided it would be preferable to switch to `deps.edn` because it ships with Clojure itself, making no need to use Leiningen. My only hesitation (besides needing to switch them all over) is that Leiningen seems to be refusing to die, loads of popular projects still use it, and people are used to being able to type `lein test` to run all the tests, while with `deps.edn` the easiest way is to set an alias to pull in the [Cognitect test runner](https://github.com/cognitect-labs/test-runner), although every Clojure editor plug-in includes a way of easily running tests.

It's also very significant that Leiningen (`project.clj`) uses twice the resources to run Clojure programs, since it starts up a whole extra JVM for the REPL... for me that's enough reason to switch right there.

**Comment by ErikSchierboom** [comment]
@porkostomus Ah great! Is is hard to port the old exercises to the new structure? We'd also need to updat the test runner. We _could_ temporarily disable concept exercises if you don't have the time to do this.

**Comment by RoelofWobben** [comment]
Is it difficult to make the switch ?

**Comment by ErikSchierboom** [comment]
@porkostomus I think pulling in the Cognitect test runner by default seems like a great idea.

**Comment by cstby** [comment]
Looks like this issue can be closed out? Or is there still work to be done?

**Comment by porkostomus** [comment]
Yeah, all exercises have both files now so we're done here :)
