### ISSUE TITLE
Solution fails even though all tests are passing — in Web editor

### ISSUE THREAD

**Issue by ikr** [exercism/clojure#420]
0 failed, but Submit button remains disabled

https://exercism.org/tracks/clojure/exercises/bird-watcher
https://exercism.org/tracks/clojure/exercises/cars-assemble

**Comment by porkostomus** [comment]
The test runner is still under heavy development, so not all reporting works as it should. Your feedback is much appreciated because it helps us know what to fix! In cases like this, the behavior most likely indicates that there is a failing assertion that it's not telling you about. We're very sorry to have released something so buggy, but we were trying to compete with Cyberpunk...
