### ISSUE TITLE
Armstrong Numbers

### ISSUE THREAD

**Issue by db-exercism** [exercism/clojure#451]
Hi!

This is maybe not a big deal, and please close as necessary. But I want to suggest that exercise 3 - Armstrong numbers - requires too much Clojure-specifc knowledge for the basics track. I honestly thought I'd never get through Clojure, and then saw that the next problem was incredibly basic. Then I saw the syllabus and said to myself "I got this"

I am familiar with an older lisp variant, Scheme, from yesteryear. But I had to dig into the stdlib a bit to emit digits as a sequence, and use the threading macro. I also learned the use of the hash symbol.

Happy to have learned all of it, but I wonder if others get scared off.

**Comment by asifm** [comment]
I'm a new learner and here's what I think. Yes, it's a hard problem if one doesn't know how to convert between string and character or between character and integer and then how to put them together. But it's a good thing that it forced me to figure these things out because this knowledge is essential to solve latter problems.

The threading macro is never strictly needed. By hash symbol, I'm guessing you mean anonymous functions. That's a core syntax one should know early on. 

Feeling stuck — and persevering until writing a solution that passess all tests — is how learning happens.

**Comment by bobbicodes** [comment]
I appreciate the feedback, the Clojure syllabus is under heavy construction and this will help improve it.

I'm guessing this issue is due to insufficient prerequisites being set, if I'm interpreting "basics track" to mean the right thing. Armstrong numbers is not part of the actual syllabus - it's a "practice" exercise which is meant to be optional.
