### ISSUE TITLE
Tracks on Tracks on Tracks: Incorrect implementation of task 4 passes test for task 4, but fails test for task 6

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/clojure#558]
I picked up the Clojure track for the Summer of Sexps and I'm writing this issue as somebody extremely new to Lisps 🙂 

I was solving the Tracks on Tracks on Tracks when I got stuck on the last task, task 6, which failed with error:

```
An unexpected error occurred:
java.lang.ClassCastException: clojure.lang.Cons cannot be cast to clojure.lang.IPersistentStack
```

As a newbie, I didn't really understand the error so I just looked up the correct solution. Turns out I made a mistake in task 4 (I used `pop` instead of `rest`), but the test for task 4 was passing for my solution. See screenshot below.

Would it be possible to add more tests for task 4 so that this type of error will be caught and reported as a problem with task 4, not task 6?

![Screenshot 2023-06-11 at 16 34 36](https://github.com/exercism/clojure/assets/7852553/a725bb06-f4ba-48a6-8d1e-ad0294ec7012)

**Comment by bobbicodes** [comment]
I'm actually in the process of rewriting this exercise because there are several problems with it. It was the first concept exercise anyone made and we didn't know what we were doing yet.

I'm actually confused why it didn't work with `pop`. In fact, folks use it all the time for that function as it differs from `rest` only in its handling of the empty list.

The exercise is also out of place, because there's an elegant way to do the composition in the final task, but it hasn't been taught yet. Since there's a better exercise for teaching lists (Card Games, I think?), so I think I'm going to do port that one, and rework this exercise to teach function composition, which is what task 6 is really asking for.

**Comment by tasxatzial** [comment]
`pop` isn't incorrect here. The reason it fails is because the add-language uses `cons` instead of `conj`. This transforms the initial `PersistentList` to a `Cons` object and `pop` doesn't work on them.

**Comment by bobbicodes** [comment]
Closing this because the exercise was deprecated (see #584). This exercise will confuse students no more :)
