### ISSUE TITLE
Difficult to reproduce tests locally

### ISSUE THREAD

**Issue by JaumeAmoresDS** [exercism/clojure#581]
I am finding plenty of discrepancies between the results of the tests when I run them on my windows installation of clojure and the results obtained by exercism. I guess linux is used on the exercism platform. I noticed that there are exercism docker images for each track. Maybe it would be good to recommend, especially for clojure, to try and install one of these Dockers, especially to reproduce some of the exercises tests? I can point out which tests have different results, if there is interest. 
In my case, I just installed the official clojure docker image, and then installed exercism on WSL. I can also give some basic instructions about these steps, including what I did to connect VSC with the WSL docker image, if there is interest.

**Comment by bobbicodes** [comment]
Hello! Indeed, there will be minor differences because the Exercism test runner uses Babashka. This could perhaps be documented better, but there is a notice at the beginning of the syllabus: https://github.com/exercism/clojure/blob/c6789a4f39507eca5fe6d1a3d4244e89c5ff4604/exercises/concept/lucians-luscious-lasagna/src/lucians_luscious_lasagna.clj#L2
